version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'symfony-ux-turbo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_RANDOM_ROOT_PASSWORD: 'false'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  my-db:
###< doctrine/doctrine-bundle ###
